madeby_language: 'pt'
no_item: '&c&lTenha um item em Mãos!'
no_perm: '&c&lVocê não tem permissão!'
not_player: 'Apenas jogadores podem executar este comando!'
header:
    main: '&b&lEncantamentos'
    c_fish: '&b&lEncantamentos &7- &c&lPesca'
    c_armor: '&b&lEncantamentos &7&l- &c&lArmaduras'
    c_sword: '&b&lEncantamentos &7&l- &c&lEspadas'
    c_bows: '&b&lEncantamentos &7&l- &c&lArcos'
    c_all: '&b&lEncantamentos &7&l- &c&lFerramentas'
    c_trident: '&b&lEncantamentos &7&l- &c&lTridentes'
    c_crossbow: '&b&lEncantamentos &7&l- &c&lBesta'
    lvls: '&b&lEncantamentos &7&l- &d&lNíveis'
    end: '&b&lEncantamentos'
categories:
    fish: '&c&lVaras de Pesca'
    armor: '&c&lArmaduras'
    sword: '&c&lEspadas'
    bows: '&c&lArcos'
    trident: '&c&lTridentes'
    all: '&c&lFerramentas'
    crossbow: '&c&lBesta'
    main: '&6&lMenu Principal'
levels:
    one: '&a&lNível I'
    two: '&a&lNível II'
    three: '&a&lNível III'
    four: '&a&lNível IV'
    five: '&a&lNível V'
    six: '&a&lNível VI'
    seven: '&a&lNível VII'
    eight: '&a&lNível VIII'
    nine: '&a&lNível IX'
    ten: '&a&lNível X'
end:
    item: '&2&lEncantado!'
    main: '&6&lRetornar ao Menu Principal'
    close: '&4&lFechar'
enchantment:
    sword:
        sharpness: '&5&lAfiação'
        bane: '&5&lRuína dos Artrópodes'
        smite: '&5&lJulgamento'
        looting: '&5&lPilhagem'
        fire_aspect: '&5&lAspecto Flamejante'
        knockback: '&5&lRepulsão'
        sweeping_edge: '&5&lAlcance'
    armor:
        protection: '&5&lProteção'
        blast_protection: '&5&lProteção contra Explosões'
        fire_protection: '&5&lProteção contra Fogo'
        projectile_protection: '&5&lProteção contra Projéteis'
        feather_falling: '&5&lPeso Pena'
        respiration: '&5&lRespiração'
        aqua_affinity: '&5&lAfinidade Aquática'
        thorns: '&5&lEspinhos'
        depth_strider: '&5&lPassos Profundos'
        frost_walker: '&5&lPassos Gelados'
    all:
        efficiency: '&5&lEficiência'
        silk_touch: '&5&lToque Suave'
        unbreaking: '&5&lInquebrabilidade'
        fortune: '&5&lFortuna'
        mending: '&5&lRemendo'
        curse_of_vanishing: '&4&lMaldição do Desaparecimento'
        curse_of_binding: '&4&lMaldição da Ligação'
    bow:
        power: '&5&lForça'
        punch: '&5&lImpacto'
        flame: '&5&lChama'
        infinity: '&5&lInfinidade'
    fish:
        luck_of_the_sea: '&5&lSorte do Mar'
        lure: '&5&lIsca'
    trident:
        loyalty: '&5&lLealdade'
        channeling: '&5&lCondutividade'
        riptide: '&5&lCorrenteza'
        impaling: '&5&lPerfuração'
    crossbow:
        multishot: '&5&lTiro Múltiplo'
        quick_charge: '&5&lCarga Rápida'
        piercing: '&5&lPerfuração'